In [1]:
import pandas as pd
import sqlalchemy as sal
import pyodbc

engine = sal.create_engine(r"mssql+pyodbc://AKSHAYKUMAR\SQLEXPRESS01/master?"r"driver=ODBC+DRIVER+18+FOR+SQL+SERVER&"r"TrustServerCertificate=yes")
conn = engine.connect()

In [11]:
def extract():
    df_orders = pd.read_csv('orders.csv')
    df_returns = pd.read_csv('returns.csv')
    return df_orders, df_returns

def transform(df_orders, df_returns):
    df = pd.merge(df_orders, df_returns, how='inner', left_on='Order_ID', right_on='return_order_id')
    return df

def load(df):
    df.to_sql('orders_final', con=conn, index=False, if_exists='replace')
    conn.commit()

In [12]:
df_orders, df_returns = extract()

df = transform(df_orders, df_returns)

load(df)

In [13]:
df

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country/Region,City,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,return_order_id,return_reason
0,2718,CA-2018-100006,07-09-2018,13-09-2018,Standard Class,DK-13375,Dennis Kane,Consumer,United States,New York City,...,TEC-PH-10002075,Technology,Phones,AT&T EL51110 DECT,377.970,3,0.0,109.6113,CA-2018-100006,bad quality
1,3084,CA-2018-100328,28-01-2018,03-02-2018,Standard Class,JC-15340,Jasper Cacioppo,Consumer,United States,New York City,...,OFF-BI-10000343,Office Supplies,Binders,"Pressboard Covers with Storage Hooks, 9 1/2"" x...",3.928,1,0.2,1.3257,CA-2018-100328,bad quality
2,3836,CA-2018-100363,08-04-2018,15-04-2018,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,OFF-FA-10000611,Office Supplies,Fasteners,Binder Clips by OIC,2.368,2,0.2,0.8288,CA-2018-100363,wrong product
3,3837,CA-2018-100363,08-04-2018,15-04-2018,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,OFF-PA-10004733,Office Supplies,Paper,Things To Do Today Spiral Book,19.008,3,0.2,6.8904,CA-2018-100363,wrong product
4,6288,CA-2018-100090,08-07-2018,12-07-2018,Standard Class,EB-13705,Ed Braxton,Corporate,United States,San Francisco,...,FUR-TA-10003715,Furniture,Tables,Hon 2111 Invitation Series Corner Table,502.488,3,0.2,-87.9354,CA-2018-100090,wrong product
5,6289,CA-2018-100090,08-07-2018,12-07-2018,Standard Class,EB-13705,Ed Braxton,Corporate,United States,San Francisco,...,OFF-BI-10001597,Office Supplies,Binders,"Wilson Jones Ledger-Size, Piano-Hinge Binder, ...",196.704,6,0.2,68.8464,CA-2018-100090,wrong product
6,6315,CA-2018-100762,24-11-2018,29-11-2018,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,OFF-AR-10000380,Office Supplies,Art,"Hunt PowerHouse Electric Pencil Sharpener, Blue",151.920,4,0.0,45.5760,CA-2018-100762,bad quality
7,6316,CA-2018-100762,24-11-2018,29-11-2018,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,OFF-LA-10003930,Office Supplies,Labels,"Dot Matrix Printer Tape Reel Labels, White, 50...",196.620,2,0.0,96.3438,CA-2018-100762,bad quality
8,6317,CA-2018-100762,24-11-2018,29-11-2018,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,OFF-PA-10001815,Office Supplies,Paper,Xerox 1885,144.120,3,0.0,69.1776,CA-2018-100762,bad quality
9,6318,CA-2018-100762,24-11-2018,29-11-2018,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,OFF-PA-10004082,Office Supplies,Paper,Adams Telephone Message Book w/Frequently-Call...,15.960,2,0.0,7.9800,CA-2018-100762,bad quality
10,6569,CA-2018-100678,18-04-2018,22-04-2018,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Houston,...,OFF-AR-10001868,Office Supplies,Art,Prang Dustless Chalk Sticks,2.688,2,0.2,1.0080,CA-2018-100678,others
11,6570,CA-2018-100678,18-04-2018,22-04-2018,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Houston,...,FUR-CH-10002602,Furniture,Chairs,DMI Arturo Collection Mission-style Design Woo...,317.058,3,0.3,-18.1176,CA-2018-100678,others
12,6571,CA-2018-100678,18-04-2018,22-04-2018,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Houston,...,OFF-EN-10000056,Office Supplies,Envelopes,Cameo Buff Policy Envelopes,149.352,3,0.2,50.4063,CA-2018-100678,others
13,6572,CA-2018-100678,18-04-2018,22-04-2018,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Houston,...,TEC-AC-10000474,Technology,Accessories,Kensington Expert Mouse Optical USB Trackball ...,227.976,3,0.2,28.4970,CA-2018-100678,others
14,9020,CA-2018-100706,16-12-2018,18-12-2018,Second Class,LE-16810,Laurel Elliston,Consumer,United States,Springfield,...,TEC-AC-10001314,Technology,Accessories,Case Logic 2.4GHz Wireless Keyboard,99.980,2,0.0,7.9984,CA-2018-100706,others
15,9021,CA-2018-100706,16-12-2018,18-12-2018,Second Class,LE-16810,Laurel Elliston,Consumer,United States,Springfield,...,FUR-FU-10002268,Furniture,Furnishings,Ultra Door Push Plate,29.460,6,0.0,9.7218,CA-2018-100706,others
16,9441,CA-2018-100391,25-05-2018,29-05-2018,Standard Class,BW-11065,Barry Weirich,Consumer,United States,New York City,...,OFF-PA-10001471,Office Supplies,Paper,Strathmore Photo Frame Cards,14.620,2,0.0,6.7252,CA-2018-100391,wrong product
17,9515,CA-2018-100293,14-03-2018,18-03-2018,Standard Class,NF-18475,Neil Französisch,Home Office,United States,Jacksonville,...,OFF-PA-10000176,Office Supplies,Paper,Xerox 1887,91.056,6,0.2,31.8696,CA-2018-100293,bad quality
18,9660,CA-2018-100860,26-03-2018,30-03-2018,Second Class,CS-12505,Cindy Stewart,Consumer,United States,Pomona,...,OFF-LA-10001982,Office Supplies,Labels,Smead Alpha-Z Color-Coded Name Labels First Le...,18.750,5,0.0,9.0000,CA-2018-100860,wrong product

In [14]:
df_sql = pd.read_sql_query('select * from orders_final', conn)
df_sql

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country/Region,City,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,return_order_id,return_reason
0,2718,CA-2018-100006,07-09-2018,13-09-2018,Standard Class,DK-13375,Dennis Kane,Consumer,United States,New York City,...,TEC-PH-10002075,Technology,Phones,AT&T EL51110 DECT,377.970,3,0.0,109.6113,CA-2018-100006,bad quality
1,3084,CA-2018-100328,28-01-2018,03-02-2018,Standard Class,JC-15340,Jasper Cacioppo,Consumer,United States,New York City,...,OFF-BI-10000343,Office Supplies,Binders,"Pressboard Covers with Storage Hooks, 9 1/2"" x...",3.928,1,0.2,1.3257,CA-2018-100328,bad quality
2,3836,CA-2018-100363,08-04-2018,15-04-2018,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,OFF-FA-10000611,Office Supplies,Fasteners,Binder Clips by OIC,2.368,2,0.2,0.8288,CA-2018-100363,wrong product
3,3837,CA-2018-100363,08-04-2018,15-04-2018,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,OFF-PA-10004733,Office Supplies,Paper,Things To Do Today Spiral Book,19.008,3,0.2,6.8904,CA-2018-100363,wrong product
4,6288,CA-2018-100090,08-07-2018,12-07-2018,Standard Class,EB-13705,Ed Braxton,Corporate,United States,San Francisco,...,FUR-TA-10003715,Furniture,Tables,Hon 2111 Invitation Series Corner Table,502.488,3,0.2,-87.9354,CA-2018-100090,wrong product
5,6289,CA-2018-100090,08-07-2018,12-07-2018,Standard Class,EB-13705,Ed Braxton,Corporate,United States,San Francisco,...,OFF-BI-10001597,Office Supplies,Binders,"Wilson Jones Ledger-Size, Piano-Hinge Binder, ...",196.704,6,0.2,68.8464,CA-2018-100090,wrong product
6,6315,CA-2018-100762,24-11-2018,29-11-2018,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,OFF-AR-10000380,Office Supplies,Art,"Hunt PowerHouse Electric Pencil Sharpener, Blue",151.920,4,0.0,45.5760,CA-2018-100762,bad quality
7,6316,CA-2018-100762,24-11-2018,29-11-2018,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,OFF-LA-10003930,Office Supplies,Labels,"Dot Matrix Printer Tape Reel Labels, White, 50...",196.620,2,0.0,96.3438,CA-2018-100762,bad quality
8,6317,CA-2018-100762,24-11-2018,29-11-2018,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,OFF-PA-10001815,Office Supplies,Paper,Xerox 1885,144.120,3,0.0,69.1776,CA-2018-100762,bad quality
9,6318,CA-2018-100762,24-11-2018,29-11-2018,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,OFF-PA-10004082,Office Supplies,Paper,Adams Telephone Message Book w/Frequently-Call...,15.960,2,0.0,7.9800,CA-2018-100762,bad quality
10,6569,CA-2018-100678,18-04-2018,22-04-2018,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Houston,...,OFF-AR-10001868,Office Supplies,Art,Prang Dustless Chalk Sticks,2.688,2,0.2,1.0080,CA-2018-100678,others
11,6570,CA-2018-100678,18-04-2018,22-04-2018,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Houston,...,FUR-CH-10002602,Furniture,Chairs,DMI Arturo Collection Mission-style Design Woo...,317.058,3,0.3,-18.1176,CA-2018-100678,others
12,6571,CA-2018-100678,18-04-2018,22-04-2018,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Houston,...,OFF-EN-10000056,Office Supplies,Envelopes,Cameo Buff Policy Envelopes,149.352,3,0.2,50.4063,CA-2018-100678,others
13,6572,CA-2018-100678,18-04-2018,22-04-2018,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Houston,...,TEC-AC-10000474,Technology,Accessories,Kensington Expert Mouse Optical USB Trackball ...,227.976,3,0.2,28.4970,CA-2018-100678,others
14,9020,CA-2018-100706,16-12-2018,18-12-2018,Second Class,LE-16810,Laurel Elliston,Consumer,United States,Springfield,...,TEC-AC-10001314,Technology,Accessories,Case Logic 2.4GHz Wireless Keyboard,99.980,2,0.0,7.9984,CA-2018-100706,others
15,9021,CA-2018-100706,16-12-2018,18-12-2018,Second Class,LE-16810,Laurel Elliston,Consumer,United States,Springfield,...,FUR-FU-10002268,Furniture,Furnishings,Ultra Door Push Plate,29.460,6,0.0,9.7218,CA-2018-100706,others
16,9441,CA-2018-100391,25-05-2018,29-05-2018,Standard Class,BW-11065,Barry Weirich,Consumer,United States,New York City,...,OFF-PA-10001471,Office Supplies,Paper,Strathmore Photo Frame Cards,14.620,2,0.0,6.7252,CA-2018-100391,wrong product
17,9515,CA-2018-100293,14-03-2018,18-03-2018,Standard Class,NF-18475,Neil Französisch,Home Office,United States,Jacksonville,...,OFF-PA-10000176,Office Supplies,Paper,Xerox 1887,91.056,6,0.2,31.8696,CA-2018-100293,bad quality
18,9660,CA-2018-100860,26-03-2018,30-03-2018,Second Class,CS-12505,Cindy Stewart,Consumer,United States,Pomona,...,OFF-LA-10001982,Office Supplies,Labels,Smead Alpha-Z Color-Coded Name Labels First Le...,18.750,5,0.0,9.0000,CA-2018-100860,wrong product

In [6]:
def extract():
    df_products = pd.read_csv('products.csv')
    df_products_db = pd.read_sql_query('select * from products', conn)
    return df_products, df_products_db

def transform(df_products, df_products_db):
    df_merged = pd.merge(left=df_products, right=df_products_db, how='left', on = 'product_id')
    df_insert = df_merged[df_merged['product_name_y'].isna()]
    df_insert_final = df_insert.iloc[: , 0:3]
    df_insert_final.columns = df_products_db.columns

    df_update = df_merged[df_merged['product_name_y'].notna()]
    df_update_final = df_update.iloc[: , 0:3]
    df_update_final.columns = df_products_db.columns
    return df_insert_final, df_update_final

def load_staging(df_update_final):
    df_update_final.to_sql('products_stg', con=conn, index=False, if_exists='replace')
    conn.commit()

def updates():
    query = sal.text("update products set price=products_stg.price from products_stg where products.product_id = products_stg.product_id")
    p = conn.execute(query)
    conn.commit()

def inserts(df_insert_final):
    df_insert_final.to_sql('products', con=conn, index=False, if_exists='append')
    conn.commit()

In [7]:
df_products, df_products_db = extract()

df_insert_final, df_update_final = transform(df_products, df_products_db)

load_staging(df_update_final)

inserts(df_insert_final)

updates()

In [13]:
df_insert_final

   product_id product_name  price
3           5         Ipad  45000

In [14]:
df_update_final

   product_id product_name  price
0           1    HP Laptop  57000
1           2    Iphone 13  65000
2           3  Dell Tablet  36000

In [15]:
df_products

   product_id product_name  price
0           1    HP Laptop  57000
1           2    Iphone 13  65000
2           3  Dell Tablet  36000
3           5         Ipad  45000

In [16]:
df_products_db

   product_id   product_name    price
0           1      HP Laptop  50000.0
1           4  Lenovo Laptop  80000.0
2           2      Iphone 13  60000.0
3           3    Dell Tablet  30000.0